#!/bin/sh
set -eu

command=${SSH_ORIGINAL_COMMAND:-}

if ! printf '%s\n' "$command" |
  grep -Eq '^deploy [1-9][0-9]*\.0\.0 [0-9a-f]{40}$'; then
  printf '%s\n' "Only validated major WatchPair deployments are allowed." >&2
  exit 64
fi

set -- $command
exec sudo -n /usr/local/sbin/watchpair-ci-deploy "$2" "$3"
