#!/bin/sh
set -eu

command=${SSH_ORIGINAL_COMMAND:-}

if ! printf '%s\n' "$command" |
  grep -Eq '^(deploy|status) [0-9]+\.[0-9]+\.[0-9]+ [0-9a-f]{40}$'; then
  printf '%s\n' "Only validated WatchPair deployment commands are allowed." >&2
  exit 64
fi

set -- $command
exec sudo -n /usr/local/sbin/watchpair-ci-deploy "$1" "$2" "$3"
